### ISSUE TITLE
검색 ERROR(사용자 profile이 null이여서 발생)

### ISSUE THREAD

**Issue by altmshfkgudtjr** [velopert/velog-server#15]
**바로가기**
(아래링크로 들어가면 bug가 발생하지않으니, 직접 검색해주시길 바랍니다.)
[https://velog.io/search/?q=오더링](https://velog.io/search/?q=오더링)
[https://velog.io/search/?q=서비스](https://velog.io/search/?q=서비스)
[https://velog.io/search/?q=kkam2ya](https://velog.io/search/?q=kkam2ya)

## 버그발생
먼저 메인에서 "서비스" 또는 "오더링" 이라고 검색할 시, 에러 페이지와 동시에, 클라이언트 Console창에 게시글 Json이 출력됩니다. 
## 버그내용
**TypeError: Cannot read property 'thumbnail' of null**

해당 버그는 velog-client/src/components/common/PostCard.tsx 파일의 154줄에서 발생하였으며, 
optimizeImage(post.user.profile.thumbnail || userThumbnail,120,) 과정에서 profile이 null이여서 Error가 발생한 것 같습니다. 더 자세하게 알아보니, kkam2ya 라는 User가 Issue의 원인이였으며, 동일하게 kkam2ya라고 검색했을 시에도 동일한 Error가 발생하였습니다. 해당 User의 profile에 대한 정보가 없다고 추측합니다.
(역으로 파다보니, velog-client/src/lib/graphql/user.ts 파일에서 UserProfile이 null입니다.)

**Comment by velopert** [comment]
감사합니다 :) 오늘 확인해보겠습니다.

**Comment by velopert** [comment]
다른 사용자가 또 이러한 이슈가 발생할지는 모르겠는데..
이런 문제있는 데이터가 있을지라도 크래시가 나지 않고 만약 누르면 404가 보여지게끔 수정을 했습니다.
감사합니다.
