### ISSUE TITLE
object 값으로 나와

### ISSUE THREAD

**Issue by dohankk** [velopert/velog-server#153]
![image](https://github.com/velopert/velog-server/assets/106723173/895c95b4-e690-45d3-8c82-3e53fb758d1c)

**Comment by winverse** [comment]
불편을 드려서 죄송합니다.
계정명을 알 수 있을까요? velog.io/@velopert 이런식으로 주소의 @뒤에 오는 값입니다. 

홈 -> 헤더 프로필 클릭-> 내 벨로그 페이지에서 
URL @ 시작하는 부분이 계정명입니다.
