### ISSUE TITLE
태그검색이 포스트를 불러오지 못하는 문제가 있습니다.

### ISSUE THREAD

**Issue by FeelingXD** [velopert/velog-server#168]
## What'problem 🤔
다음은 #인기 라는 태그를 이용해서 검색한 예제입니다.

v2->v3로 변경된 이후 태그 검색 기능이 deprecate 된건지 검색을 하여도 관련 포스트를 가져오지 못하고있습니다.

![image](https://github.com/velopert/velog-server/assets/45274316/fd0b3170-fab9-4335-8cfb-ee2e8a2b939a)

![image](https://github.com/velopert/velog-server/assets/45274316/3cb6d975-fb55-4ac0-b5a4-1d3b9907f63c)
개발자 도구로 확인해보았을때 graphql 에대한 쿼리가 정상적으로 호출하는것으로 보이나 포스트를 여전히 가져오지 못하고 있습니다.

**Comment by winverse** [comment]
안녕하세요 Velog를 이용해주시고 의견 주셔서 감사합니다 :)

해당 기능은 안타깝게도 DB에 부하를 일으켜 잠시 비활성화된 상태 입니다.
향후 업데이트를 통해서 다시 서비스를 제공해드리도록 하겠습니다.

이용에 불편을 드려 죄송합니다.
