### ISSUE TITLE
임시저장 포스트 출간시 에러발생

### ISSUE THREAD

**Issue by MinhoLee93** [velopert/velog-server#18]
안녕하세요. :)
포스트 작성시 에러가 발생해 문의드립니다.

기존에 임시저장했던 글을 보완후 금일 출간버튼을 클릭하니 
서버에서 아래와 같은 에러가 발생합니다.
계속 출간버튼을 눌러도 화면 이동이 없어서
그냥 취소하고 메인으로 나오니 글 업데이트는 정상적으로 되었습니다.

글 URL : https://velog.io/write?id=c192ab8a-c415-4c44-8767-95026155046a

![image](https://user-images.githubusercontent.com/50879621/75153662-48955300-574f-11ea-8271-0f5ea5d8d2b6.png)

**Comment by velopert** [comment]
어제 레디스 서버 쪽에 잠깐 장애가 있었는데 그로인하여 발생한 문제가 아닐까 싶습니다.
레디스 서버 또는 검색 서버 쪽에 문제가 발생해도 글쓰는데 오류가 발생하지 않도록, 내부 로직 수정해볼게요 :)

**Comment by velopert** [comment]
또 발생하면 이슈 열어주세요~
