### ISSUE TITLE
Protect your secrets

### ISSUE THREAD

**Issue by cometkim** [velopert/velog-server#21]
여기 좀 실제 시크릿들 히스토리에 들어간 것 같은데 괜찮나요.....??

서드파티 시크릿들은 좀 안괜찮을 것 같은데 클라이언트/키 전부 revoke 하시고 깃 히스토리도 한번 밀어버리셔야 되지 않으려나 싶네요 ㅎㅎ;

설정 파일:
- https://github.com/velopert/velog-server/blob/master/.env.development
- https://github.com/velopert/velog-server/blob/master/serverless.yml

커밋 로그:
```
INFO[2020-02-27T21:51:16Z] No leaks detected. 151 commits audited in 1 second 33 milliseconds 3 microseconds
```
(이전 velog repo랑 좀 햇갈렸는데 거기도 커밋에 좀 leaked secrets 있네요)

**Comment by velopert** [comment]
아! 
해당 시크릿키들은 개발전용이라 노출되도 문제 없는 키 입니다!

진짜 키 노출했으면 큰일 나겠죠 하핫 ;)

신경써줘서 감사해요~
