### ISSUE TITLE
게시글 답글 메일에서 "답글 달기" 버튼 클릭시 404

### ISSUE THREAD

**Issue by cadenzah** [velopert/velog-server#24]
<img width="757" alt="스크린샷 2020-03-09 오전 9 48 30" src="https://user-images.githubusercontent.com/18698124/76174527-2558b200-61eb-11ea-8b6e-5ed1cf3e201e.png">

여기서 "답글 달기" 버튼을 누르면 새 창으로 연결되는데
404 에러가 나옵니다.

주소가 아래같은데

https://velog.io/@ckstn0777/graphql-node-07-authentication?comment_id=b498cd19-0144-4554-b34f-fa90f695dc6a?comment_id=b498cd19-0144-4554-b34f-fa90f695dc6a

댓글id를 두번 쿼리 파라미터로 보내고 있었던 것 같습니다

**Comment by velopert** [comment]
링크가 이상한곳으로 가고있더군요!
ㅋㅋㅋ 방금 고쳤습니다.

클라이언트에서 추후 comment_id 를 가르키는곳을 바로 보여주게하는건 나중에.. 해볼게요!

**Comment by cadenzah** [comment]
으아아니 글 쓰고있던 중인데......ㅋㅋㅋㅋㅋ (제가 적다 말고 잘못 눌렀나봅니다)
너무 빠른 피드백 감사합니다...ㅎㅎ
