### ISSUE TITLE
포스팅 url 마침표에 대한 예외처리가 필요합니다.

### ISSUE THREAD

**Issue by nupamore** [velopert/velog-server#26]
![image](https://user-images.githubusercontent.com/11649322/76682669-4f720000-6641-11ea-8710-4c88c3837cbc.png)
![image](https://user-images.githubusercontent.com/11649322/76682673-5bf65880-6641-11ea-8641-41ac3f9c26f7.png)

카톡, 디스코드 등의 메신저에서는 마침표까지 하이퍼링크가 걸리지 않아서 클릭하면 404로 가버리네요.

**Comment by velopert** [comment]
클라 및 서버측에서 둘 다 고쳤습니다.
기존 URL의 경우엔 수동작업 하도록 할게요.

**Comment by velopert** [comment]
아.. 이게 맨 마지막에 있는 .만 좀 이상하게 작동하는거군요
아예 . 을 없앨게 아니라 해당 문자로 끝나는걸 해야겠군요...
