### ISSUE TITLE
특정 포스트에서 다음 포스트 카드가 보여지지 않습니다.

### ISSUE THREAD

**Issue by Sayakie** [velopert/velog-server#43]
예를 들어, [포스트](https://velog.io/@adam2/Github-Action-%EC%A3%BC%EC%9A%94-%EB%AC%B8%EB%B2%95)에서 시리즈 섹션에서는 정상적으로 다음 포스트가 보여지지만 하단 다음 포스트 카드가 보여지지가 않습니다.

**Comment by velopert** [comment]
헛~ 매우 이상하네요. 조사해보겠습니다!

**Comment by velopert** [comment]
시리즈 다음 포스트가 비공개 포스트라 발생한 이슈였습니다.
해당 비공개 포스트가 작성하다가 포기 (?) 한 포스트여서, 우선 제대로 작동하게 만들기 위하여 수작업으로 시리즈에서 제외시키긴 했는데요, 이 이슈가 완벽히 해결이 된 것 은 아니라..

추후 시리즈 비공개 관련 작업하게 될 때 함께 처리하겠습니다.
해당 이슈 연결시키고 이 이슈는 닫겠습니다.

감사합니다!
