### ISSUE TITLE
social 로그인이 동작하지 않아요

### ISSUE THREAD

**Issue by lenon461** [velopert/velog-server#6]
![image](https://user-images.githubusercontent.com/12893887/74213859-6dfd7800-4cde-11ea-9ff7-adb63f837671.png)

구글 버튼 클릭시 아래주소로 리다이렉트 되고 로그인이 되지 않아요.

![image](https://user-images.githubusercontent.com/12893887/74213868-7bb2fd80-4cde-11ea-9427-a2442f409c8c.png)

https://v2.velog.io/ 사이트가 아예 응답을 하지 않는것 같기도 합니다.

**Comment by velopert** [comment]
https://v2.velog.io/

에 들어갔을 때 hello world 가 뜨나요?

**Comment by lenon461** [comment]
무슨이유에선지.. 제 데스크탑 환경에서만 동작하지 않네요

다른기기로 들어갈때는 잘 나옵니다
