### ISSUE TITLE
시리즈 목록에서 포스트를 새 창으로 열기 했을 때 SSR 오류 발생

### ISSUE THREAD

**Issue by cadenzah** [velopert/velog-server#60]
[시리즈 목록](https://velog.io/@cadenzah/series/Master-the-JavaScript-Interview) 상에서 각 포스트를 그대로 링크 클릭하여 열람할 때에는 문제가 없는데, 각 포스트를 새 창으로 열기로 보고자 할 때 (Chrome 기준 Cmd + 클릭) 아래와 같은 JSON 응답이 반환되며 페이지가 비정상 로드됩니다.

```json
{"msg":"SSR has crashed","e":{}}
```

**Comment by moaikang** [comment]
구글 같은 외부 사이트에서 벨로그에 접속할 때, 새 창이 아니더라도
```
{"msg":"SSR has crashed","e":{}}
```
아래와 같은 JSON 응답이 반환됩니다.

**Comment by modolee** [comment]
내부에서 접속 후 새로고침을 누르는 경우에도 동일한 에러 메세지가 나오고 있습니다.

**Comment by velopert** [comment]
앗! 그렇군요 ㅠㅠ 고치러갑니다요

**Comment by velopert** [comment]
고쳐졌습니다.
